/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 62
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_DASH_GT = 2,
  anon_sym_LT_DASH = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_LBRACK = 6,
  anon_sym_RBRACK = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  sym_op = 10,
  anon_sym_SLASH = 11,
  anon_sym_COMMA = 12,
  sym_number = 13,
  sym__in_name_inner = 14,
  sym__node_name_inner = 15,
  sym_trail_inner = 16,
  sym_source_file = 17,
  sym__line = 18,
  sym_arrow_line = 19,
  sym_norm_line = 20,
  sym_arrow = 21,
  sym_in_name = 22,
  sym_node_name = 23,
  sym_nice = 24,
  sym_trail = 25,
  sym_trailtrail = 26,
  aux_sym_source_file_repeat1 = 27,
  aux_sym_trailtrail_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LT_DASH] = "<-",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_op] = "op",
  [anon_sym_SLASH] = "/",
  [anon_sym_COMMA] = ",",
  [sym_number] = "number",
  [sym__in_name_inner] = "_in_name_inner",
  [sym__node_name_inner] = "_node_name_inner",
  [sym_trail_inner] = "trail_inner",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_arrow_line] = "arrow_line",
  [sym_norm_line] = "norm_line",
  [sym_arrow] = "arrow",
  [sym_in_name] = "in_name",
  [sym_node_name] = "node_name",
  [sym_nice] = "nice",
  [sym_trail] = "trail",
  [sym_trailtrail] = "trailtrail",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_trailtrail_repeat1] = "trailtrail_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_op] = sym_op,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_number] = sym_number,
  [sym__in_name_inner] = sym__in_name_inner,
  [sym__node_name_inner] = sym__node_name_inner,
  [sym_trail_inner] = sym_trail_inner,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_arrow_line] = sym_arrow_line,
  [sym_norm_line] = sym_norm_line,
  [sym_arrow] = sym_arrow,
  [sym_in_name] = sym_in_name,
  [sym_node_name] = sym_node_name,
  [sym_nice] = sym_nice,
  [sym_trail] = sym_trail,
  [sym_trailtrail] = sym_trailtrail,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_trailtrail_repeat1] = aux_sym_trailtrail_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_op] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym__in_name_inner] = {
    .visible = false,
    .named = true,
  },
  [sym__node_name_inner] = {
    .visible = false,
    .named = true,
  },
  [sym_trail_inner] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_arrow_line] = {
    .visible = true,
    .named = true,
  },
  [sym_norm_line] = {
    .visible = true,
    .named = true,
  },
  [sym_arrow] = {
    .visible = true,
    .named = true,
  },
  [sym_in_name] = {
    .visible = true,
    .named = true,
  },
  [sym_node_name] = {
    .visible = true,
    .named = true,
  },
  [sym_nice] = {
    .visible = true,
    .named = true,
  },
  [sym_trail] = {
    .visible = true,
    .named = true,
  },
  [sym_trailtrail] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_trailtrail_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 25,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 19,
  [57] = 57,
  [58] = 41,
  [59] = 42,
  [60] = 53,
  [61] = 43,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '\n', 8,
        '(', 11,
        ')', 12,
        ',', 25,
        '-', 2,
        '/', 24,
        '<', 1,
        '[', 13,
        ']', 14,
        '{', 15,
        '}', 16,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 1:
      if (lookahead == '-') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == '[') ADVANCE(13);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(23);
      END_STATE();
    case 4:
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(23);
      END_STATE();
    case 5:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(23);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == '<') ADVANCE(18);
      if (lookahead == '[') ADVANCE(13);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(23);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_op);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == '<') ADVANCE(18);
      if (lookahead == '[') ADVANCE(13);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(23);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_op);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(23);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_op);
      if (lookahead == '>') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(23);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_op);
      if (lookahead == '[') ADVANCE(13);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(23);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_op);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(23);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_op);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_op);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__in_name_inner);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ')') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__in_name_inner);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ')') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__node_name_inner);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__node_name_inner);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_trail_inner);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_trail_inner);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_trail_inner);
      if (eof) ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',') ADVANCE(32);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 33},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 33},
  [15] = {.lex_state = 33},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 33},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 33},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 29},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 27},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 33},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 5},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 27},
  [61] = {.lex_state = 29},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(49),
    [sym__line] = STATE(37),
    [sym_arrow_line] = STATE(37),
    [sym_norm_line] = STATE(37),
    [sym_arrow] = STATE(8),
    [sym_in_name] = STATE(5),
    [sym_node_name] = STATE(17),
    [sym_nice] = STATE(47),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_DASH_GT] = ACTIONS(5),
    [anon_sym_LT_DASH] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [sym_op] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym__line] = STATE(24),
    [sym_arrow_line] = STATE(24),
    [sym_norm_line] = STATE(24),
    [sym_arrow] = STATE(8),
    [sym_in_name] = STATE(5),
    [sym_node_name] = STATE(17),
    [sym_nice] = STATE(47),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(5),
    [anon_sym_LT_DASH] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [sym_op] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym__line] = STATE(50),
    [sym_arrow_line] = STATE(50),
    [sym_norm_line] = STATE(50),
    [sym_arrow] = STATE(8),
    [sym_in_name] = STATE(5),
    [sym_node_name] = STATE(17),
    [sym_nice] = STATE(47),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_DASH_GT] = ACTIONS(19),
    [anon_sym_LT_DASH] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(22),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(28),
    [sym_op] = ACTIONS(31),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(34), 6,
      anon_sym_DASH_GT,
      anon_sym_LT_DASH,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_op,
  [12] = 5,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(36), 1,
      sym_op,
    STATE(18), 1,
      sym_node_name,
    STATE(57), 1,
      sym_nice,
  [28] = 3,
    ACTIONS(40), 1,
      anon_sym_SLASH,
    STATE(34), 1,
      sym_trail,
    ACTIONS(38), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [39] = 3,
    ACTIONS(40), 1,
      anon_sym_SLASH,
    STATE(28), 1,
      sym_trail,
    ACTIONS(42), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [50] = 4,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    STATE(35), 1,
      sym_in_name,
    STATE(36), 1,
      sym_node_name,
  [63] = 3,
    ACTIONS(40), 1,
      anon_sym_SLASH,
    STATE(40), 1,
      sym_trail,
    ACTIONS(48), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [74] = 3,
    ACTIONS(40), 1,
      anon_sym_SLASH,
    STATE(32), 1,
      sym_trail,
    ACTIONS(50), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [85] = 3,
    ACTIONS(54), 1,
      anon_sym_COMMA,
    STATE(13), 1,
      aux_sym_trailtrail_repeat1,
    ACTIONS(52), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [96] = 4,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 1,
      anon_sym_LF,
    ACTIONS(60), 1,
      sym_trail_inner,
    STATE(23), 1,
      sym_trailtrail,
  [109] = 3,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_trailtrail_repeat1,
    ACTIONS(62), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [120] = 4,
    ACTIONS(60), 1,
      sym_trail_inner,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 1,
      anon_sym_LF,
    STATE(38), 1,
      sym_trailtrail,
  [133] = 4,
    ACTIONS(60), 1,
      sym_trail_inner,
    ACTIONS(70), 1,
      ts_builtin_sym_end,
    ACTIONS(72), 1,
      anon_sym_LF,
    STATE(31), 1,
      sym_trailtrail,
  [146] = 3,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_trailtrail_repeat1,
    ACTIONS(74), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [157] = 3,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(36), 1,
      sym_op,
    STATE(57), 1,
      sym_nice,
  [167] = 3,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(79), 1,
      sym_op,
    STATE(48), 1,
      sym_nice,
  [177] = 1,
    ACTIONS(81), 3,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_op,
  [183] = 3,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    ACTIONS(83), 1,
      anon_sym_LF,
    ACTIONS(85), 1,
      sym_trail_inner,
  [193] = 1,
    ACTIONS(74), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [199] = 3,
    ACTIONS(85), 1,
      sym_trail_inner,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(89), 1,
      anon_sym_LF,
  [209] = 1,
    ACTIONS(66), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [214] = 2,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 1,
      anon_sym_LF,
  [221] = 1,
    ACTIONS(95), 2,
      anon_sym_LBRACE,
      sym_op,
  [226] = 2,
    ACTIONS(97), 1,
      anon_sym_COMMA,
    ACTIONS(99), 1,
      sym_number,
  [233] = 1,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [238] = 1,
    ACTIONS(48), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [243] = 1,
    ACTIONS(103), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [248] = 2,
    ACTIONS(105), 1,
      anon_sym_COMMA,
    ACTIONS(107), 1,
      sym_number,
  [255] = 1,
    ACTIONS(56), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [260] = 1,
    ACTIONS(109), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [265] = 2,
    ACTIONS(111), 1,
      anon_sym_COMMA,
    ACTIONS(113), 1,
      sym_number,
  [272] = 1,
    ACTIONS(42), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [277] = 2,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    STATE(27), 1,
      sym_node_name,
  [284] = 1,
    ACTIONS(115), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [289] = 2,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 1,
      anon_sym_LF,
  [296] = 1,
    ACTIONS(117), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [301] = 1,
    ACTIONS(119), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [306] = 1,
    ACTIONS(50), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [311] = 1,
    ACTIONS(121), 1,
      anon_sym_RPAREN,
  [315] = 1,
    ACTIONS(123), 1,
      anon_sym_RBRACK,
  [319] = 1,
    ACTIONS(125), 1,
      sym__node_name_inner,
  [323] = 1,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
  [327] = 1,
    ACTIONS(129), 1,
      anon_sym_COMMA,
  [331] = 1,
    ACTIONS(131), 1,
      sym_op,
  [335] = 1,
    ACTIONS(133), 1,
      sym_op,
  [339] = 1,
    ACTIONS(135), 1,
      sym_op,
  [343] = 1,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
  [347] = 1,
    ACTIONS(93), 1,
      anon_sym_LF,
  [351] = 1,
    ACTIONS(139), 1,
      sym_number,
  [355] = 1,
    ACTIONS(105), 1,
      anon_sym_COMMA,
  [359] = 1,
    ACTIONS(141), 1,
      sym__in_name_inner,
  [363] = 1,
    ACTIONS(143), 1,
      anon_sym_COMMA,
  [367] = 1,
    ACTIONS(85), 1,
      sym_trail_inner,
  [371] = 1,
    ACTIONS(145), 1,
      anon_sym_LBRACK,
  [375] = 1,
    ACTIONS(147), 1,
      sym_op,
  [379] = 1,
    ACTIONS(149), 1,
      anon_sym_RPAREN,
  [383] = 1,
    ACTIONS(151), 1,
      anon_sym_RBRACK,
  [387] = 1,
    ACTIONS(153), 1,
      sym__in_name_inner,
  [391] = 1,
    ACTIONS(155), 1,
      sym__node_name_inner,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 12,
  [SMALL_STATE(6)] = 28,
  [SMALL_STATE(7)] = 39,
  [SMALL_STATE(8)] = 50,
  [SMALL_STATE(9)] = 63,
  [SMALL_STATE(10)] = 74,
  [SMALL_STATE(11)] = 85,
  [SMALL_STATE(12)] = 96,
  [SMALL_STATE(13)] = 109,
  [SMALL_STATE(14)] = 120,
  [SMALL_STATE(15)] = 133,
  [SMALL_STATE(16)] = 146,
  [SMALL_STATE(17)] = 157,
  [SMALL_STATE(18)] = 167,
  [SMALL_STATE(19)] = 177,
  [SMALL_STATE(20)] = 183,
  [SMALL_STATE(21)] = 193,
  [SMALL_STATE(22)] = 199,
  [SMALL_STATE(23)] = 209,
  [SMALL_STATE(24)] = 214,
  [SMALL_STATE(25)] = 221,
  [SMALL_STATE(26)] = 226,
  [SMALL_STATE(27)] = 233,
  [SMALL_STATE(28)] = 238,
  [SMALL_STATE(29)] = 243,
  [SMALL_STATE(30)] = 248,
  [SMALL_STATE(31)] = 255,
  [SMALL_STATE(32)] = 260,
  [SMALL_STATE(33)] = 265,
  [SMALL_STATE(34)] = 272,
  [SMALL_STATE(35)] = 277,
  [SMALL_STATE(36)] = 284,
  [SMALL_STATE(37)] = 289,
  [SMALL_STATE(38)] = 296,
  [SMALL_STATE(39)] = 301,
  [SMALL_STATE(40)] = 306,
  [SMALL_STATE(41)] = 311,
  [SMALL_STATE(42)] = 315,
  [SMALL_STATE(43)] = 319,
  [SMALL_STATE(44)] = 323,
  [SMALL_STATE(45)] = 327,
  [SMALL_STATE(46)] = 331,
  [SMALL_STATE(47)] = 335,
  [SMALL_STATE(48)] = 339,
  [SMALL_STATE(49)] = 343,
  [SMALL_STATE(50)] = 347,
  [SMALL_STATE(51)] = 351,
  [SMALL_STATE(52)] = 355,
  [SMALL_STATE(53)] = 359,
  [SMALL_STATE(54)] = 363,
  [SMALL_STATE(55)] = 367,
  [SMALL_STATE(56)] = 371,
  [SMALL_STATE(57)] = 375,
  [SMALL_STATE(58)] = 379,
  [SMALL_STATE(59)] = 383,
  [SMALL_STATE(60)] = 387,
  [SMALL_STATE(61)] = 391,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_norm_line, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_norm_line, 2, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_norm_line, 3, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_norm_line, 4, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trailtrail, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trail, 4, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trail, 4, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trailtrail, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trail, 5, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trail, 5, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trail, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trail, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_trailtrail_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_trailtrail_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_in_name, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trailtrail, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trailtrail, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trailtrail, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_name, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arrow_line, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arrow, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_norm_line, 5, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arrow_line, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trail, 6, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_name, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nice, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [137] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_in_name, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dih(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "dih",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
